# Generated by Django 3.0.6 on 2020-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session13live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
